'use client'

import Image from 'next/image'
import { useMemo, useState } from 'react'
import { ArrowRight, Check, ChevronDown, Menu, Minus, Plus, ShoppingBag, Sparkles, Truck, X } from 'lucide-react'

type Product = { id: string; name: string; price: number; image?: string; dimensions?: string; tag?: string }

const castles: Product[] = [
  { id: 'fee', name: 'Château Fée', price: 60, dimensions: '2,4 × 2,1 × 2 m', image: '/images/chateau-fee.webp' },
  { id: 'fort', name: 'Château Fort', price: 70, dimensions: '2,8 × 2,6 × 2,1 m', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chateau-fort-QWNaYbO8E2jJl893eQm2ZAEWaD3CQZ.webp' },
  { id: 'licorne', name: 'Château Licorne', price: 70, dimensions: '3,4 × 3,8 × 2,5 m', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chateau-licorne-29WAebFGtVA2l3VZyhE2LV6sGXRX26.webp' },
  { id: 'splash', name: 'Château Splash', price: 80, dimensions: '3,9 × 3 × 2 m', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/chateau-splash-BWeML8a60pnAHRk77TYkzPFFbypvoU.webp' },
  { id: 'palais', name: 'Palais Blanc', price: 80, dimensions: '2,4 × 2,5 × 2,4 m', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/palais-blanc-HiqWTA7whUxtltBKmiPhsMlkmHTr2z.webp' },
  { id: 'ninja', name: 'Ninja Parc', price: 80, dimensions: '4,9 × 2,4 × 1,9 m', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-parc-rX8HLbniLrEK9tWeKYqwrj1jmmZMNc.webp' },
  { id: 'papou', name: 'Papou Pompier', price: 80, dimensions: '2,7 × 5,6 × 2,1 m', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/papou-pompier-WeQPQBqXUVnBrpdoDKgMrI6u8kaV73.webp' },
  { id: 'mega', name: 'Mega Parc', price: 90, dimensions: '3,4 × 4 × 2,6 m', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mega-parc-Y7ilAb6C2XNle4QDFOFReftkc5e4Nu.webp' },
  { id: 'bubble', name: 'Bubble House XL', price: 120, dimensions: '4,8 × 3 × 2,2 m', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bubble-house-mpdkAFeRflnrgBeGM2ob0Jx65NU4hi.webp', tag: 'Nouveau' },
]
const parks: Product[] = [
  { id: 'mini', name: 'Mini Kids Park', price: 349, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mini-kids-park-6RoaIiIYQZc6Vo3uAvLb8uwbOUAIYB.webp', tag: 'Dès 349 €' },
  { id: 'maxi', name: 'Maxi Kids Park', price: 399, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/maxi-kids-park-ljpUXbA42akT4DdmnetvmaMssbCsJJ.webp', tag: 'Dès 399 €' },
  { id: 'royal', name: 'Royal Kids Park', price: 449, image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/royal-kids-park-P5QWMDziwoSo3OqvPxxEcCbCPumxdT.webp', tag: 'Dès 449 €' },
]
const games: Product[] = [
  { id: 'tetris', name: 'Tetris Tumble', price: 45, image: '/images/tetris-tumble.webp' }, { id: 'babyfoot', name: 'Baby-foot', price: 45, image: '/images/baby-foot.webp' }, { id: 'pool', name: 'Piscine à balles', price: 55, image: '/images/piscine-balles.webp' }, { id: 'cible', name: 'Cible foot géante', price: 45, image: '/images/cible-foot.webp' }, { id: 'tir', name: 'Cible de tir', price: 45, image: '/images/cible-tir.webp' }, { id: 'bowling', name: 'Bowling arcade', price: 45, image: '/images/bowling.webp' }, { id: 'puissance', name: 'Puissance 4 géant', price: 35, image: '/images/puissance-4.webp' }, { id: 'haches', name: 'Lancer de haches', price: 45, image: '/images/lancer-haches.webp' }, { id: 'basket', name: 'Basket-ball arcade', price: 45, image: '/images/basket.webp' },
]

export default function Page() {
  const [cart, setCart] = useState<Record<string, number>>({})
  const [openCart, setOpenCart] = useState(false)
  const [menu, setMenu] = useState(false)
  const [faq, setFaq] = useState(0)
  const all = [...parks, ...castles, ...games]
  const items = all.filter((p) => cart[p.id])
  const count = Object.values(cart).reduce((a, b) => a + b, 0)
  const total = useMemo(() => items.reduce((s, p) => s + p.price * cart[p.id], 0), [items, cart])
  const add = (id: string) => setCart((c) => ({ ...c, [id]: (c[id] || 0) + 1 }))
  const change = (id: string, amount: number) => setCart((c) => ({ ...c, [id]: Math.max(0, (c[id] || 0) + amount) }))
  const whatsapp = `https://wa.me/33698702341?text=${encodeURIComponent(`Bonjour Jump’In Paris ! Je souhaite réserver :\n${items.map((p) => `• ${p.name} x${cart[p.id]} — ${p.price * cart[p.id]} €`).join('\n')}\n\nTotal estimatif : ${total} €\nPouvez-vous me confirmer les disponibilités ?`)}`

  return <main className="min-h-screen bg-background">
    <div className="bg-primary px-5 py-2 text-center text-xs font-bold text-primary-foreground">Livraison, installation et retrait en Île-de-France</div>
    <header className="sticky top-0 z-40 border-b border-border/70 bg-background/95 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-3 lg:px-8"><a href="#accueil" className="flex items-center gap-2"><Image src="/images/logo.webp" alt="Jump’In Paris" width={64} height={64} className="-my-2 object-contain"/><span className="hidden font-heading font-black text-primary sm:block">JUMP’IN PARIS</span></a><nav className="hidden gap-7 text-sm font-bold lg:flex"><a href="#parks">Aires de jeux</a><a href="#catalogue">Châteaux</a><a href="#jeux">Jeux</a><a href="#livraison">Livraison</a></nav><div className="flex gap-2"><button onClick={() => setOpenCart(true)} className="relative flex items-center gap-2 rounded-full bg-accent px-4 py-2.5 text-sm font-bold text-accent-foreground"><ShoppingBag size={17}/><span className="hidden sm:inline">Panier</span>{count > 0 && <b className="grid size-5 place-items-center rounded-full bg-background text-xs text-primary">{count}</b>}</button><button aria-label="Ouvrir le menu" onClick={() => setMenu(!menu)} className="rounded-full border border-border p-2.5 lg:hidden"><Menu size={18}/></button></div></div>{menu && <nav className="flex flex-col gap-4 border-t border-border px-5 py-4 text-sm font-bold lg:hidden"><a href="#parks" onClick={() => setMenu(false)}>Aires de jeux</a><a href="#catalogue" onClick={() => setMenu(false)}>Châteaux</a><a href="#jeux" onClick={() => setMenu(false)}>Jeux</a><a href="#livraison" onClick={() => setMenu(false)}>Livraison</a></nav>}</header>
    <section id="accueil" className="mx-auto grid max-w-7xl items-center gap-8 px-5 pb-14 pt-12 lg:grid-cols-[.85fr_1.15fr] lg:px-8 lg:pb-20 lg:pt-20"><div><p className="mb-5 inline-flex items-center gap-2 rounded-full bg-secondary/30 px-3 py-1.5 text-xs font-black uppercase tracking-wider text-primary"><Sparkles size={14}/> La fête commence ici</p><h1 className="font-heading text-5xl font-black leading-[.98] tracking-tight text-primary sm:text-7xl">Louez le <span className="text-accent">waouh.</span></h1><p className="mt-6 max-w-lg text-lg leading-8 text-muted-foreground">Châteaux gonflables, aires de jeux et animations pour des anniversaires qui restent en mémoire.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#catalogue" className="inline-flex items-center gap-2 rounded-full bg-secondary px-6 py-3.5 text-sm font-black text-secondary-foreground shadow-lg">Voir les structures <ArrowRight size={17}/></a><a href="#contact" className="inline-flex items-center gap-2 rounded-full border border-primary/25 px-6 py-3.5 text-sm font-bold text-primary">Devis rapide</a></div><div className="mt-8 flex flex-wrap gap-5 text-sm font-bold"><span className="flex items-center gap-2"><Check size={17} className="text-accent"/> Installation incluse</span><span className="flex items-center gap-2"><Check size={17} className="text-accent"/> Réponse WhatsApp</span></div></div><div className="relative min-h-[330px] lg:min-h-[500px]"><div className="absolute inset-8 rounded-[3rem] bg-secondary/25 rotate-3"/><Image src={parks[2].image!} alt="Royal Kids Park avec toboggan et piscine à balles" fill priority className="relative object-contain drop-shadow-2xl" sizes="(max-width: 1024px) 100vw, 55vw"/><span className="absolute bottom-3 right-2 rounded-full bg-accent px-4 py-2 text-sm font-black text-accent-foreground shadow-lg">Des souvenirs XXL</span></div></section>
    <section id="parks" className="bg-primary px-5 py-14 text-primary-foreground lg:px-8 lg:py-20"><div className="mx-auto max-w-7xl"><div className="mb-9 flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.2em] text-secondary">Les grands formats</p><h2 className="mt-2 font-heading text-4xl font-black sm:text-5xl">Aires de jeux</h2></div><p className="hidden max-w-xs text-sm leading-6 text-primary-foreground/70 md:block">Pour les anniversaires, kermesses et événements qui voient grand.</p></div><div className="grid gap-5 md:grid-cols-3">{parks.map((p, i) => <ProductCard key={p.id} product={p} onAdd={add}/>)}</div></div></section>
    <section id="catalogue" className="bg-muted/60 px-5 py-14 lg:px-8 lg:py-20"><div className="mx-auto max-w-7xl"><div className="mb-9 max-w-xl"><p className="text-xs font-black uppercase tracking-[.2em] text-accent">Le catalogue</p><h2 className="mt-2 font-heading text-4xl font-black text-primary sm:text-5xl">Choisissez votre château</h2><p className="mt-4 leading-7 text-muted-foreground">Ajoutez vos favoris au panier. Nous confirmons la disponibilité par WhatsApp.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{castles.map((p, i) => <ProductCard key={p.id} product={p} onAdd={add} compact/>)}</div></div></section>
    <section id="jeux" className="mx-auto max-w-7xl px-5 py-14 lg:px-8 lg:py-20"><div className="mb-9 flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-accent">Pour tous les âges</p><h2 className="mt-2 font-heading text-4xl font-black text-primary sm:text-5xl">Jeux intérieurs & extérieurs</h2></div><span className="hidden rounded-full bg-secondary/30 px-3 py-2 text-xs font-black text-primary sm:block">Nouveautés 2026</span></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{games.map((p, i) => <ProductCard key={p.id} product={p} onAdd={add} compact/>)}</div></section>
    <section id="livraison" className="bg-secondary px-5 py-14 lg:px-8 lg:py-20"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2 lg:items-center"><div><Truck size={34} className="text-primary"/><h2 className="mt-4 font-heading text-4xl font-black text-primary sm:text-5xl">On livre, on installe, vous profitez.</h2><p className="mt-4 max-w-lg leading-7 text-secondary-foreground/75">À partir de 100 € hors Aire de Jeux. Click & Collect disponible.</p><div className="mt-6 grid max-w-md grid-cols-2 gap-3"><div className="rounded-2xl bg-background p-5"><b className="text-sm text-muted-foreground">Cercle bleu</b><p className="mt-2 font-heading text-3xl font-black text-primary">59 €</p></div><div className="rounded-2xl bg-primary p-5 text-primary-foreground"><b className="text-sm text-secondary">Cercle rouge</b><p className="mt-2 font-heading text-3xl font-black">99 €</p></div></div><p className="mt-4 text-sm font-bold text-primary">Hors zone : livraison sur devis.</p></div><div className="overflow-hidden rounded-3xl border-4 border-background bg-background shadow-xl"><Image src="/images/zone-livraison.webp" alt="Carte des zones de livraison en Île-de-France" width={1873} height={937} className="h-auto w-full"/></div></div></section>
    <section id="contact" className="mx-auto max-w-7xl px-5 py-14 lg:px-8 lg:py-20"><div className="rounded-[2rem] bg-primary p-8 text-primary-foreground sm:p-12 lg:flex lg:items-center lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-secondary">Une question ?</p><h2 className="mt-3 font-heading text-4xl font-black sm:text-5xl">Votre fête mérite mieux.</h2><p className="mt-4 text-primary-foreground/70">Parlez-nous de votre date et de votre événement.</p></div><a href="https://wa.me/33698702341?text=Bonjour%20Jump’In%20Paris%20!%20Je%20souhaite%20un%20devis." target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 rounded-full bg-secondary px-6 py-3.5 text-sm font-black text-secondary-foreground lg:mt-0">Demander un devis <ArrowRight size={17}/></a></div><div className="mt-12"><p className="text-xs font-black uppercase tracking-[.2em] text-muted-foreground">Questions fréquentes</p><div className="mt-4 divide-y divide-border border-y border-border">{['Quand réserver ?', 'La livraison comprend-elle l’installation ?', 'Puis-je venir récupérer le matériel ?'].map((q, i) => <div key={q}><button onClick={() => setFaq(faq === i ? -1 : i)} className="flex w-full items-center justify-between py-5 text-left font-bold text-primary">{q}<ChevronDown size={18} className={faq === i ? 'rotate-180' : ''}/></button>{faq === i && <p className="pb-5 text-sm leading-7 text-muted-foreground">Dès que votre date est connue. La livraison inclut l’installation et le retrait selon la zone. Le Click & Collect est disponible sur demande.</p>}</div>)}</div></div></section>
    <footer className="border-t border-border px-5 py-8 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-3 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between"><p>© 2026 Jump’In Paris · Location de structures gonflables</p><a href="tel:+33698702341" className="font-bold text-primary">+33 6 98 70 23 41</a></div></footer>
    {openCart && <div className="fixed inset-0 z-50 bg-primary/40" onClick={() => setOpenCart(false)}><aside onClick={(e) => e.stopPropagation()} className="ml-auto flex h-full w-full max-w-md flex-col bg-background p-6 shadow-2xl"><div className="flex items-center justify-between border-b border-border pb-5"><div><p className="text-xs font-bold text-muted-foreground">Votre sélection</p><h2 className="font-heading text-2xl font-black text-primary">Mon panier</h2></div><button aria-label="Fermer le panier" onClick={() => setOpenCart(false)} className="rounded-full border border-border p-2"><X size={18}/></button></div><div className="flex-1 overflow-y-auto py-5">{items.length === 0 ? <div className="grid h-full place-items-center text-center"><ShoppingBag className="mx-auto text-muted-foreground"/><p className="mt-3 font-bold text-primary">Votre panier est vide</p><p className="mt-1 text-sm text-muted-foreground">Ajoutez une structure pour commencer.</p></div> : <div className="flex flex-col gap-4">{items.map((p) => <div key={p.id} className="flex gap-3"><div className="relative size-20 shrink-0 overflow-hidden rounded-xl bg-muted"><Image src={p.image!} alt={p.name} fill className="object-contain"/></div><div className="min-w-0 flex-1"><p className="truncate font-bold text-primary">{p.name}</p><p className="text-sm text-muted-foreground">{p.price} €</p><div className="mt-2 flex items-center gap-2"><button onClick={() => change(p.id, -1)} className="grid size-7 place-items-center rounded-full border border-border"><Minus size={13}/></button><span className="w-4 text-center text-sm font-bold">{cart[p.id]}</span><button onClick={() => change(p.id, 1)} className="grid size-7 place-items-center rounded-full border border-border"><Plus size={13}/></button></div></div></div>)}</div>}</div>{items.length > 0 && <div className="border-t border-border pt-5"><div className="mb-4 flex justify-between font-heading text-xl font-black text-primary"><span>Total estimatif</span><span>{total} €</span></div><a href={whatsapp} target="_blank" rel="noreferrer" className="flex w-full items-center justify-center rounded-full bg-accent px-5 py-4 text-sm font-black text-accent-foreground">Commander sur WhatsApp</a><p className="mt-3 text-center text-xs text-muted-foreground">Vous pouvez aussi envoyer une capture de votre panier.</p></div>}</aside></div>}
  </main>
}

function ProductCard({ product, onAdd, compact = false }: { product: Product; onAdd: (id: string) => void; index: number; compact?: boolean }) { return <article className="group overflow-hidden rounded-3xl border border-border bg-background shadow-sm transition-all hover:-translate-y-1 hover:shadow-xl"><div className={`relative bg-muted/40 ${compact ? 'aspect-square' : 'aspect-[1.15]'}`}><Image src={product.image!} alt={`${product.name} à louer en Île-de-France`} fill className="object-contain p-3 transition-transform duration-500 group-hover:scale-105" sizes="(max-width: 768px) 100vw, 33vw"/>{product.tag && <span className="absolute left-3 top-3 rounded-full bg-secondary px-3 py-1 text-xs font-black text-secondary-foreground">{product.tag}</span>}</div><div className="p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-heading text-lg font-black text-primary">{product.name}</h3>{product.dimensions && <p className="mt-1 text-xs text-muted-foreground">{product.dimensions}</p>}</div><p className="whitespace-nowrap font-heading text-2xl font-black text-primary">{product.price} €</p></div><button onClick={() => onAdd(product.id)} className="mt-4 flex w-full items-center justify-center gap-2 rounded-full bg-primary px-4 py-3 text-sm font-bold text-primary-foreground transition-colors hover:bg-accent">Ajouter au panier <Plus size={16}/></button></div></article> }

function Placeholder({ label }: { label: string }) { return <div className="grid h-full place-items-center bg-muted p-4 text-center text-sm font-bold text-muted-foreground">{label}</div> }

